@startuml
class MtpQualityCode {
    - bit32 _value
--
    + MtpQualityCode(const string &dpeQc)
    + bool getQualityGood()
    - void setQcCB(const string &dpe, const bit32 &value)

    ..events..
    + void qualityGoodChanged(const bool &qualityGood)
}
@enduml