@startuml
!include source/Hilfsklassen/ViewModel/MtpViewModelBase.puml
!include source/Hilfsklassen/View/MtpRefBase.puml

class MtpViewBase{
    - mapping _shapes
--
    # MtpViewBase(MtpViewModelBase viewModel, const mapping &shapes)
    # MtpViewModelBase getViewModel()
    # shape extractShape(const string &shapeName)
    # {abstract} void initializeShapes()
}

MtpViewModelBase "1" --* "1" MtpViewBase : _viewModel
MtpViewBase <|-- MtpRefBase

class MtpViewRef {
    # MtpViewRef(MtpViewModelBase viewModel, const mapping &shapes)
    + void openFaceplate()
}

MtpViewBase <|-- MtpViewRef

class MtpViewFaceplateSettings{
    + MtpViewFaceplateSettings(MtpViewModelBase viewModel, const mapping &shapes)
    # void loadPanel(const string &fileName, const string &panelName)
}
MtpViewBase <|-- MtpViewFaceplateSettings
@enduml