@startuml AnaMon
!include source/Hilfsklassen/MtpViewModelBase.puml
!include source/Hilfsklassen/MtpUnit.puml
!include source/Hilfsklassen/MtpValueLimit.puml

class AnaMon
{
    - float _value
    - float _valueScaleMin
    - float _valueScaleMax
--
    + AnaMon(const string &dp)
    + WQC getWQC()
    + OSLevel getOSLevel()
    + float getValue()
    + float getValueScaleMin()
    + float getValueScaleMax()
    + MtpUnit getValueUnit()
    + MtpValueLimitFloat getAlertHighLimit()
    + MtpValueLimitFloat getWarningHighLimit()
    + MtpValueLimitFloat getToleranceHighLimit()
    + MtpValueLimitFloat getToleranceLowLimit()
    + MtpValueLimitFloat getWarningLowLimit()
    + MtpValueLimitFloat getAlertLowLimit()
    ' DPE: V
    - void setValueCB(const string &dpe, const float &value)

    ..events..
    + void valueChanged(const float &value)
}

MtpViewModelBase <|-- AnaMon
' DPE: WQC
WQC "1" --* "1" AnaMon : _wqc
' DPE: OSLevel
OSLevel "1" --* "1" AnaMon : _osLevel
' DPE: VUnit
MtpUnit "1" --* "1" AnaMon : _valueUnit
' DPE: VAHLim, VAHEn, VAHAct
MtpValueLimitFloat "1" --* "1" AnaMon : _alertHighLimit
' DPE: VWHLim, VWHEn, VWHAct
MtpValueLimitFloat "1" --* "1" AnaMon : _warningHighLimit
' DPE: VTHLim, VTHEn, VTHAct
MtpValueLimitFloat "1" --* "1" AnaMon : _toleranceHighLimit
' DPE: VTLLim, VTLEn, VTLAct
MtpValueLimitFloat "1" --* "1" AnaMon : _toleranceLowLimit
' DPE: VWLLim, VWLEn, VWLAct
MtpValueLimitFloat "1" --* "1" AnaMon : _warningLowLimit
' DPE: VALLim, VALEn, VALAct
MtpValueLimitFloat "1" --* "1" AnaMon : _alertLowLimit

class MtpViewBase
{
    - mapping _shapes

    # MtpViewBase(MtpViewModelBase viewModel, const mapping &shapes)
    # MtpViewModelBase getViewModel()
    # shape extractShape(const string &shapeName)
    # {abstract} void initializeShapes()
}

MtpViewModelBase "1" --* "1" MtpViewBase : _viewModel

class AnaMonFaceplateHome
{
}

class AnaMonFaceplateSettings1
{

}

class AnaMonFaceplateSettings2
{

}

class MtpFaceplateAlarmBase
{

}

MtpViewBase <|-- MtpFacePlateAlarmBase

class AnaMonFaceplateAlarm
{

}

MtpFacePlateAlarmBase <|-- AnaMonFaceplateAlarm

class MtpFaceplateTrendBase
{

}

MtpViewBase <|-- MtpFaceplateTrendBase

class AnaMonFaceplateTrend
{

}

MtpFaceplateTrendBase <|-- AnaMonFaceplateTrend

MtpViewBase <|-- AnaMonFaceplateHome
AnaMon "1" --* "1" AnaMonFaceplateHome : _viewModel
MtpViewBase <|-- AnaMonFaceplateSettings1
AnaMon "1" --* "1" AnaMonFaceplateSettings1 : _viewModel
MtpViewBase <|-- AnaMonFaceplateSettings2
AnaMon "1" --* "1" AnaMonFaceplateSettings2 : _viewModel
AnaMon "1" --* "1" AnaMonFaceplateAlarm : _viewModel
AnaMon "1" --* "1" AnaMonFaceplateTrend : _viewModel


class AnaMonRef 
{

}

MtpViewBase <|-- AnaMonRef
AnaMon "1" --* "1" AnaMonRef : _viewModel
@enduml