@startuml AnaManInt

class AnaManInt
{
    - float _valueOut
    - float _valueScaleMin
    - float _valueScaleMax
    - float _valueManual
    - float _valueInternal
    - float _valueReadback
    - float _valueFeedback
    - bool _valueMinExceeded
    - bool _valueMaxExceeded

    + AnaManInt(const string &dp)
    + WQC getWQC()
    + OSLevel getOSLevel()
    + float getValueOut()
    + float getValueScaleMin()
    + float getValueScaleMax()
    + float getValueManual()
    + float getValueInternal()
    + float getValueReadback()
    + float getValueFeedback()
    + Source getSource()
    + Unit getValueUnit()
    + bool getValueMinExceeded()
    + bool getValueMaxExceeded()
    + void setValueManual(const float &valueManual)
    ' DPE: VOut
    - void setValueOutCB(const string &dpe, const float &valueOut)
    ' DPE: VFbk
    - void setValueFeedbackCB(const string &dpe, const float &valueFeedback)
    ' DPE: VMin
    - void setValueMinExceededCB(const string &dpe, const bool &minExceeded)
    ' DPE: VMax
    - void setValueMaxExceededCB(const string &dpe, const bool &maxExceeded)
    ' DPE: VInt
    - void setValueInternalCB(const string &dpe, const float &valueInternal)
    ' DPE: VSclMin
    - void setValueScaleMinCB(const string &dpe, const float &valueScaleMin)
    ' DPE: VSclMax
    - void setValueScaleMaxCB(const string &dpe, const float &valueScaleMax)

    ..events..
    + void valueOutChanged(const bool &value)
    + void valueFeedbackChanged(const bool &value)
    + void valueMinExceededChanged(const bool &minExceeded)
    + void valueMaxExceededChanged(const bool &maxExceeded)
    + void valueInternalChanged(const float &valueInternal)
    + void valueScaleMinChanged(const float &valueScaleMin)
    + void valueScaleMaxChanged(const float &valueScaleMax)
}

MtpViewModelBase <|-- AnaManInt
' DPE: WQC
WQC "1" --* "1" AnaManInt : _wqc
' DPE: OSLevel
OSLevel "1" --* "1" AnaManInt : _osLevel
' DPE: SrcChannel, SrcManAut, SrcIntAut, SrcManOp, SrcIntOp, SrcManAct, SrcIntAct
MtpSource "1" --* "1" AnaManInt : _source
' DPE: VUnit
MtpUnit "1" --* "1" AnaManInt : _valueUnit

@enduml