@startuml
!include source/Hilfsklassen/ViewModel/MtpViewModelBase.puml
!include source/Hilfsklassen/ViewModel/MtpUnit.puml
!include source/Hilfsklassen/ViewModel/MtpValueLimit.puml
!include source/Hilfsklassen/ViewModel/MtpQualityCode.puml
!include source/Hilfsklassen/ViewModel/MtpOsLevel.puml
!include source/Hilfsklassen/View/MtpViewBase.puml
!include source/Hilfsklassen/View/MtpFaceplateAlarm.puml
!include source/Hilfsklassen/View/MtpFaceplateTrendBase.puml

class AnaMon {
    - float _value
    - float _valueScaleMin
    - float _valueScaleMax
--
    + AnaMon(const string &dp)
    + MtpQualityCode getWqc()
    + MtpOsLevel getOsLevel()
    + float getValue()
    + float getValueScaleMin()
    + float getValueScaleMax()
    + MtpUnit getUnit()
    + MtpValueLimitFloat getAlertHighLimit()
    + MtpValueLimitFloat getWarningHighLimit()
    + MtpValueLimitFloat getToleranceHighLimit()
    + MtpValueLimitFloat getToleranceLowLimit()
    + MtpValueLimitFloat getWarningLowLimit()
    + MtpValueLimitFloat getAlertLowLimit()
    ' DPE: V
    - void setValueCB(const string &dpe, const float &value)

    ..events..
    + void valueChanged(const float &value)
}

MtpViewModelBase <|-- AnaMon
' DPE: WQC
MtpQualityCode "1" --* "1" AnaMon : _wqc
' DPE: OSLevel
MtpOsLevel"1" --* "1" AnaMon : _osLevel
' DPE: VUnit
MtpUnit "1" --* "1" AnaMon : _unit
' DPE: VAHLim, VAHEn, VAHAct
MtpValueLimitFloat "1" --* "1" AnaMon : _alertHighLimit
' DPE: VWHLim, VWHEn, VWHAct
MtpValueLimitFloat "1" --* "1" AnaMon : _warningHighLimit
' DPE: VTHLim, VTHEn, VTHAct
MtpValueLimitFloat "1" --* "1" AnaMon : _toleranceHighLimit
' DPE: VTLLim, VTLEn, VTLAct
MtpValueLimitFloat "1" --* "1" AnaMon : _toleranceLowLimit
' DPE: VWLLim, VWLEn, VWLAct
MtpValueLimitFloat "1" --* "1" AnaMon : _warningLowLimit
' DPE: VALLim, VALEn, VALAct
MtpValueLimitFloat "1" --* "1" AnaMon : _alertLowLimit

class AnaMonFaceplateHome {
    
}

class AnaMonFaceplateSettings1 {

}

class AnaMonFaceplateSettings2 {

}

class AnaMonFaceplateAlarm {

}

MtpFaceplateAlarm <|-- AnaMonFaceplateAlarm


class AnaMonFaceplateTrend {

}

MtpFaceplateTrendBase <|-- AnaMonFaceplateTrend

MtpViewBase <|-- AnaMonFaceplateHome
AnaMon "1" --* "1" AnaMonFaceplateHome : _viewModel
MtpViewBase <|-- AnaMonFaceplateSettings1
AnaMon "1" --* "1" AnaMonFaceplateSettings1 : _viewModel
MtpViewBase <|-- AnaMonFaceplateSettings2
AnaMon "1" --* "1" AnaMonFaceplateSettings2 : _viewModel
AnaMon "1" --* "1" AnaMonFaceplateAlarm : _viewModel
AnaMon "1" --* "1" AnaMonFaceplateTrend : _viewModel


class AnaMonRef {
    - shape _txtValue
    - shape _txtUnit
    - shape _rectStatus
    - bool _alertHighActive
    - bool _warningHighActive
    - bool _toleranceHighActive
    - bool _toleranceLowActive
    - bool _warningLowActive
    - bool _alertLowActive
--
    + AnaMonRef(shared_ptr<Anamon> viewModel, const mapping &shapes)
    + void openFaceplate()
    # void initializeShapes()
    - void setValueCB(const float &value)
    - void setUnit(shared_ptr<MtpUnit> unit)
    - void setStatusCB(const string &varName, const bool &active)
}

MtpViewBase <|-- AnaMonRef
AnaMon "1" --* "1" AnaMonRef : _viewModel
@enduml