@startuml AnaManInt

class MtpViewModelBase {
    - string _dp
    - bool _invalid

    # MtpViewModelBase(const string &dp)
    + bool getInvalid()
    + string getDp()
}

enum UnitType
{

}

class Unit
{
    - UnitType _value
    + string toString()
}

class Source
{
    - bool _channel
    - bool manualAutomatic
    - bool internalAutomatic
    - bool manualOperator
    - bool internalOperator
    - bool manualActive
    - bool internalActive

    # Source(const string &dp)  
    + bool getChannel() 
    + bool getManualAutomatic()
    + bool getInternalAutomatic()
    + bool getManualOperator()  
    + bool getInternalOperator()    
    + bool getManualActive()
    + bool getInternalActive()
    # void setManualActive(const bool &channel)
    # void setInternalActive(const bool &channel)

    ..events..
    + void manualActiveChanged(const bool &active)
    + void internalActiveChanged(const bool &active)
}

class AnaManInt
{
    - float _valueOut
    - float _valueScaleMin
    - float _valueScaleMax
    - float _valueManual
    - float _valueInternal
    - float _valueReadback
    - float _valueFeedback
    - bool _valueMinExceeded
    - bool _valueMaxExceeded

    + AnaManInt(const string &dp)
    + WQC getWQC()
    + OSLevel getOSLevel()
    + float getValueOut()
    + float getValueScaleMin()
    + float getValueScaleMax()
    + float getValueManual()
    + float getValueInternal()
    + float getValueReadback()
    + float getValueFeedback()
    + Source getSource()
    + Unit getValueUnit()
    + bool getValueMinExceeded()
    + bool getValueMaxExceeded()
    + void setValueManual(const float &value)

    ..events..
    + void valueOutChanged(const bool &value)
    + void valueFeedbackChanged(const bool &value)
    + void valueExceededChanged(const bool &minExceeded, const bool &maxExceeded)
    + void valueInternalChanged(const float &value)
}

MtpViewModelBase <|-- AnaManInt
WQC "1" --* "1" AnaManInt : _wqc
OSLevel "1" --* "1" AnaManInt : _osLevel
Source "1" --* "1" AnaManInt : _source
Unit "1" --* "1" AnaManInt : _valueUnit

@enduml