@startuml

class MtpViewModelBase {
    - string _dp
    - bool _invalid

    # MtpViewModelBase(const string &dp)
    + bool getInvalid()
    + string getDp()
}

class Source
{
    - bool _channel
    - bool manualAutomatic
    - bool internalAutomatic
    - bool manualOperator
    - bool internalOperator
    - bool manualActive
    - bool internalActive

    # Source(const string &dp)  
    + bool getChannel() 
    + bool getManualAutomatic()
    + bool getInternalAutomatic()
    + bool getManualOperator()  
    + bool getInternalOperator()    
    + bool getManualActive()
    + bool getInternalActive()
    + void setManualActive(const bool &channel)
    + void setInternalActive(const bool &channel)

    ..events..
    + void manualActiveChanged(const bool &active)
    + void internalActiveChanged(const bool &active)
}

class BinManInt
{
    - bool _valueOut
    - string _valueStateFalseText
    - string _valueStateTrueText
    - bool _valueManual
    - bool _valueInternal
    - bool _valueReadback
    - bool _valueFeedback

    + BinManInt(const string &dp)
    + WQC getWQC()
    + OSLevel getOSLevel()
    + bool getValueOut()
    + string getValueStateTrueText()
    + string getValueStateFalseText()
    + bool getValueManual()
    + bool getValueInternal()
    + bool getValueReadback()
    + bool getValueFeedback()
    + Source getSource()

    ..events..
    + void valueOutChanged(const bool &value)
    + void valueFeedbackChanged(const bool &value)
}

MtpViewModelBase <|-- BinManInt
WQC "1" --* "1" BinManInt : _wqc
OSLevel "1" --* "1" BinManInt : _osLevel
Source "1" --* "1" BinManInt : _source
@enduml