@startuml MonBinDrv

class MtpViewModelBase {
    - string _dp
    - bool _invalid

    # MtpViewModelBase(const string &dp)
    + bool getInvalid()
    + string getDp()
}

class State
{
    - bool _channel
    - bool _offAutomatic
    - bool _operatorAutomatic
    - bool _automaticAutomatic
    - bool _offOperator
    - bool _operatorOperator
    - bool _automaticOperator
    - bool _operatorActive
    - bool _automaticActive
    - bool _offActive

    # State(const string &dp)
    + bool getChannel()
    + bool getOffAutomatic()
    + bool getOperatorAutomatic()
    + bool getAutomaticAutomatic()
    + bool getOffOperator()
    + bool getOperatorOperator()
    + bool getAutomaticOperator()
    + bool getOperatorActive()
    + bool getAutomaticActive()
    + bool getOffActive()
    # void setOffActive(const bool &offActive)
    # void setOperatorActive(const bool &operatorActive)
    # void setAutomaticActive(const bool &automaticActive)

    ..events..
    + void offActiveChanged(const bool &active)
    + void operatorActiveChanged(const bool &active)
    + void automaticActiveChanged(const bool &active)
}

class Monitor
{
    - bool _monitorEnabled
    - bool _monitorSafePosition
    - bool _monitorStaticError
    - bool _monitorDynamicError
    - float _monitorStaticTime
    - float _monitorDynamicTime

    # Monitor(const string &dp)
    + bool getMonitorEnabled()
    + bool getMonitorSafePosition()
    + bool getMonitorStaticError()
    + bool getMonitorDynamicError()
    + float getMonitorStaticTime()
    + float getMonitorDynamicTime()
    # void setMonitorEnabled(const bool &monitorEnabled)

    ..events..
    + void monitorStaticErrorChanged(const bool &staticError)
    + void monitorDynamicErrorChanged(const bool &dynamicError)
}

class Security
{
    - bool _permissionEnabled
    - bool _permit
    - bool _interlockEnabled
    - bool _interlock
    - bool _protectionEnabled
    - bool _protect

    # Security(const string &dp)
    + bool getPermissionEnabled()
    + bool getPermit()
    + bool getInterlockEnabled()
    + bool getInterlock()
    + bool getProtectionEnabled()
    + bool getProtect()
    # void setPermit(const bool &permit)
    # void setInterlock(const bool &interlock)
    # void setProtect(const bool &protection)

    ..events..
    + void permitChanged(const bool &permit)
    + void interlockChanged(const bool &interlock)
    + void protectChanged(const bool &protect)
}

class MonBinDrv
{
    - bool _safetyposition
    - bool _safetypositionActive
    - bool _forwardEnabled
    - bool _reverseEnabled
    - bool _stopOperator
    - bool _forwardOperator
    - bool _reverseOperator
    - bool _stopAutomatic
    - bool _forwardAutomatic
    - bool _reverseAutomatic
    - bool _forwardControl
    - bool _reverseControl
    - bool _reverseFeedbackSource
    - bool _forwardFeedbackSource
    - bool _forwardFeedbackSignal
    - bool _reverseFeedbackSignal
    - bool _driveSafetyIndicator
    - bool _resetOperator
    - bool _resetAutomatic
    
    + MonBinDrv(const string &dp)
    + WQC getWQC()
    + OSLevel getOSLevel()
    + State getState()
    + Monitor getMonitor()
    + bool getSafetyPosition()
    + bool getSafetyPositionActive()
    + bool getForwardEnabled()
    + bool getReverseEnabled()
    + bool getStopOperator()
    + bool getForwardOperator()
    + bool getReverseOperator()
    + bool getStopAutomatic()
    + bool getForwardAutomatic()
    + bool getReverseAutomatic()
    + bool getForwardControl()
    + bool getReverseControl()
    + bool getReverseFeedbackSource()
    + bool getForwardFeedbackSource()
    + bool getForwardFeedbackSignal()
    + bool getReverseFeedbackSignal()
    + bool getDriveSafetyIndicator()
    + bool getResetOperator()
    + bool getResetAutomatic()
    + void setReverseFeedbackSignal(const bool &reverseFeedbackSignal)
    + void setForwardFeedbackSignal(const bool &forwardFeedbackSignal)
    + void setForwardControl(const bool &forwardControl)
    + void setReverseControl(const bool &reverseControl)

    ..events..
    + void forwardControlChanged(const bool &forwardControl)
    + void reverseControlChanged(const bool &reverseControl)
    + void forwardFeedbackSignalChanged(const bool &forwardFeedbackSignal)
    + void reverseFeedbackSignalChanged(const bool &reverseFeedbackSignal)
    + void driveSafetyIndicatorChanged(const bool &driveSafetyIndicator)
    + void safetyPositionActiveChanged(const bool &safetyPositionActive)
    + void forwardAutomaticChanged(const bool &forwardAutomatic)
    + void reverseAutomaticChanged(const bool &reverseAutomatic)
    + void stopAutomaticChanged(const bool &stopAutomatic)
}

MtpViewModelBase <|-- MonBinDrv
WQC "1" --* "1" MonBinDrv : _wqc
OSLevel "1" --* "1" MonBinDrv : _osLevel
State "1" --* "1" MonBinDrv : _state
Monitor "1" --* "1" MonBinDrv : _monitor
Security "1" --* "1" MonBinDrv : _security
@enduml