@startuml MonBinVlv

class MtpViewModelBase {
    - string _dp
    - bool _invalid

    # MtpViewModelBase(const string &dp)
    + bool getInvalid()
    + string getDp()
}

class State
{
    - bool _channel
    - bool _offAutomatic
    - bool _operatorAutomatic
    - bool _automaticAutomatic
    - bool _offOperator
    - bool _operatorOperator
    - bool _automaticOperator
    - bool _operatorActive
    - bool _automaticActive
    - bool _offActive

    # State(const string &dp)
    + bool getChannel()
    + bool getOffAutomatic()
    + bool getOperatorAutomatic()
    + bool getAutomaticAutomatic()
    + bool getOffOperator()
    + bool getOperatorOperator()
    + bool getAutomaticOperator()
    + bool getOperatorActive()
    + bool getAutomaticActive()
    + bool getOffActive()
    # void setOffActive(const bool &offActive)
    # void setOperatorActive(const bool &operatorActive)
    # void setAutomaticActive(const bool &automaticActive)

    ..events..
    + void offActiveChanged(const bool &active)
    + void operatorActiveChanged(const bool &active)
    + void automaticActiveChanged(const bool &active)
}

class Monitor
{
    - bool _monitorEnabled
    - bool _monitorSafePosition
    - bool _monitorStaticError
    - bool _monitorDynamicError
    - float _monitorStaticTime
    - float _monitorDynamicTime

    # Monitor(const string &dp)
    + bool getMonitorEnabled()
    + bool getMonitorSafePosition()
    + bool getMonitorStaticError()
    + bool getMonitorDynamicError()
    + float getMonitorStaticTime()
    + float getMonitorDynamicTime()
    # void setMonitorEnabled(const bool &monitorEnabled)

    ..events..
    + void monitorStaticErrorChanged(const bool &staticError)
    + void monitorDynamicErrorChanged(const bool &dynamicError)
}

class MonBinVlv
{
    - bool _safetyposition
    - bool _safetypositionActive
    - bool _safetypositionEnabled
    - bool _openOperator
    - bool _closeOperator
    - bool _openAutomatic
    - bool _closeAutomatic
    - bool _valveControl
    - bool _openFeedbackSource
    - bool _closeFeedbackSource
    - bool _openCheckbackSignal
    - bool _closeCheckbackSignal
    - bool _permissionEnabled
    - bool _permit
    - bool _interlockEnabled
    - bool _interlock
    - bool _protectionEnabled
    - bool _protect
    - bool _resetOperator
    - bool _resetAutomatic
    
    + MonBinVlv(const string &dp)
    + WQC getWQC()
    + OSLevel getOSLevel()
    + State getState()
    + bool getSafetyPosition()
    + bool getSafetyPositionActive()
    + bool getSafetyPositionEnabled()
    + bool getOpenOperator()
    + bool getCloseOperator()
    + bool getOpenAutomatic()
    + bool getCloseAutomatic()
    + bool getValveControl()
    + bool getOpenFeedbackSource()
    + bool getCloseFeedbackSource()
    + bool getOpenCheckbackSignal()
    + bool getCloseCheckbackSignal()
    + bool getPermissionEnabled()
    + bool getPermit()
    + bool getInterlockEnabled()
    + bool getInterlock()
    + bool getProtectionEnabled()
    + bool getProtect()
    + bool getResetOperator()
    + bool getResetAutomatic()
    + void setOpenCheckbackSignal(const bool &openCheckbackSignal)
    + void setCloseCheckbackSignal(const bool &closeCheckbackSignal)
    + void setValveControl(const bool &valveControl)
    + void setPermit(const bool &permit)
    + void setInterlock(const bool &interlock)
    + void setProtect(const bool &protection)

    ..events..
    + void openCheckBackSignalChanged(const bool &openCheckbackSignal)
    + void valveControlChanged(const bool &valveControl)
    + void closeCheckBackSignalChanged(const bool &openCheckbackSignal)
    + void permitChanged(const bool &permit)
    + void safetyPositionActiveChanged(const bool &safetyPositionActive)
}

MtpViewModelBase <|-- MonBinVlv
WQC "1" --* "1" MonBinVlv : _wqc
OSLevel "1" --* "1" MonBinVlv : _osLevel
State "1" --* "1" MonBinVlv : _state
@enduml